import type {Metadata} from 'next'
import {JetBrains_Mono} from 'next/font/google'
import './globals.css'
import {Header} from '@/components/Header'
import {AppThemeProvider} from './theme-provider'

const jetbrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
  variable: '--font-jetbrainsMono'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={jetbrainsMono.variable}>
        <AppThemeProvider>
          <Header />
          {children}
        </AppThemeProvider>
      </body>
    </html>
  )
}
